export * from './base-reducer-manager.component';
export * from './config.model';
export * from './services/base-reducer-manager.service';
export * from './+state/base-reducer-manager-state.module';
export * from './+state/base-reducer-manager.actions';
export * from './+state/base-reducer-manager.effects';
export * from './+state/base-reducer-manager.facade';
export * from './+state/base-reducer-manager.reducer';
export * from './+state/base-reducer-manager.selectors';
